### ISSUE TITLE
include decorator definition in ViolationError description

### ISSUE THREAD

**Issue by jamescasbon** [Parquery/icontract#101]
Consider this module (defined in ictb.py):
```
from icontract import require, ensure

@require(lambda x: x > 0)
def frobulate(x: int) -> int:
    return x
```
Which I use 

```
$ python -c "import ictb; ictb.frobulate(-1)"                                                                                      (tge) 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/james/Src/icontract/icontract/_checkers.py", line 291, in wrapper
    raise violation_err  # pylint: disable=raising-bad-type
  File "/home/james/Src/icontract/icontract/_checkers.py", line 285, in wrapper
    _assert_precondition(contract=contract, resolved_kwargs=resolved_kwargs)
  File "/home/james/Src/icontract/icontract/_checkers.py", line 112, in _assert_precondition
    raise ViolationError(msg)
icontract.errors.ViolationError: x > 0: x was -1
```

This is pretty good as far as it goes, but I'm always frustrated that there is no link to the source definition of frobulate with its associated requirements.  The cognitive load of finding the requirement is a little bit irritating.

I think we can do better.  In eg `require.__init__`, I can get the require definition site:

        tb = traceback.format_list(traceback.extract_stack(limit=2)[:1])[0]
        description = "\nDefined at ...\n{}".format(tb)

Giving 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/james/Src/icontract/icontract/_checkers.py", line 291, in wrapper
    raise violation_err  # pylint: disable=raising-bad-type
  File "/home/james/Src/icontract/icontract/_checkers.py", line 285, in wrapper
    _assert_precondition(contract=contract, resolved_kwargs=resolved_kwargs)
  File "/home/james/Src/icontract/icontract/_checkers.py", line 112, in _assert_precondition
    raise ViolationError(msg)
icontract.errors.ViolationError: 
Defined at ...
  File "/home/james/Src/time_gym/ictb.py", line 3, in <module>
    @require(lambda x: x > 0)
: x > 0: x was -1
```

What do you think?

**Comment by mristin** [comment]
Hi @jamescasbon ,
Thanks again for raising the issue! It is very valuable for us to see how other people are using the library and what can be improved.

I'm working on the feature and hope to have it finished by tomorrow. 

Since the condition is already included in the message, I'll just include the filename, line number and the module name. I hope that retrieving trace-back will not tip the benchmarks too much by adding too much computational overhead.

**Comment by mristin** [comment]
Hi @jamescasbon ,
The issue should be now fixed in v2.0.4 (also published on pypi).

I was not sure whether to bump a minor or a patch version. Since it's actually an omission (the location should have been included in the first place), I decided to bump the patch version.

Please let me know if there are any problems or bugs. I'm closing the issue for now.

**Comment by jamescasbon** [comment]
Thanks @mristin but from the README we only see these on class invariants.  Can we get them on require/ensure as well?

**Comment by mristin** [comment]
Hi @jamescasbon,
Do I understand you correctly: you would like readme to include an example with require/ensure or there is a functionality missing in the library?

**Comment by jamescasbon** [comment]
I believe there is missing functionality.  The location of the decorator is mentioned with @invariant but not with @require and @ensure.

You can see this in the README doctests - the patch only updated the @invariant results I believe.

**Comment by mristin** [comment]
Thanks @jamescasbon for the clarification! I'll have a look at it when I come back from holidays (May 5th 2019).

**Comment by jamescasbon** [comment]
See #106 - I think its just the location wasn't set

**Comment by mristin** [comment]
Hi @jamescasbon, 
I'm working on this right now.
