### ISSUE TITLE
*args and **kwargs not supported

### ISSUE THREAD

**Issue by v7a** [Parquery/icontract#147]
Given the following code snippet:
```py
from icontract import require


def test_args():
    @require(lambda *args: args)
    def args(*args, **kwargs):
        pass
    args(0, x=0)


def test_kwargs():
    @require(lambda **kwargs: kwargs)
    def args(*args, **kwargs):
        pass
    args(0, x=0)


def test_both():
    @require(lambda *args, **kwargs: args and kwargs)
    def args(*args, **kwargs):
        pass
    args(0, x=0)
```
I get errors saying that precondition arguments could not be set (from `_checkers.py:114`).

Unless I've missed it, the README didn't explicitly state that * and ** aren't supported. My use case is a rather generic decorator applied to some endpoints. It shouldn't matter how these endpoints are called, but they must contain a request (for the decorator to do its magic), for which I want to create a contract.

Some observations:
- `@require(lambda args: ...)` without the asterisk only passes the first argument supplied to the function to the check (i.e. 0, not [0])
- `@require(lambda kwargs: ...)` without the asterisks raises the same error

I would gladly help with fixing/implementing this since I believe every language today should provide tools for DBC, and your library does a good job. Any thoughts on the feasibility of this? :)

**Comment by mristin** [comment]
Hi @v7a ,
Thanks for reporting the issue! I'll have a look. I fear that the introspection capabilities of Python might not support it, but it can also be a bug on icontract's side. Please give me a couple of days.

**Comment by mristin** [comment]
Hi @v7a ,
I played for quite some hours trying to get `*args` and `**kwargs` working. Unfortunately, the logic of how they are populated is so complex that I gave up. There are too many edge cases and they need to be handled in a principled way.

If you don't mind, I'll point to this issue in the readme and leave the issue open? If there are enough people asking for this feature, I'll have another more thorough go at it.

Code contributions are of course welcome, so if you please, you can go ahead and implement this feature. It would be best if we could have a quick skype/teams/... meeting before as there are many potential pit falls to watch out for and design decisions to be made.

**Comment by crypdick** [comment]
@mristin Is it possible to have `require` only throw an error if the kwarg is supplied in the call?

```python
@icontract.require(lambda learning_rate: float(zoom) > 0)
def collate(**parameters) -> str:
    formatted_params = []
    for k, v in parameters.items():
        formatted_params.append("=".join((k, v)))
    
    partition_name = "|".join(formatted_params)
    return partition_name

collate(dropout="0.5")  # TypeError: The argument(s) of the precondition have not been set: ['learning_rate']. Does the original function define them? Did you supply them in the call?
```

**Comment by mristin** [comment]
@crypdick that should be actually possible with a little bit of effort. I'll try to come up with a patch today or tomorrow.

**Comment by crypdick** [comment]
I think I mean what I wrote. In the call `collate(dropout="0.5")` I did not supply a `learning_rate` kwarg, yet I got a TypeError. It would be nice if there was something akin to a `@icontract.require(lambda ..., ignore_missing=True)` so that the above example does not throw that TypeError.

**Comment by mristin** [comment]
@crypdick sorry, I misunderstood. So let me try to have a take 2 at understanding it (please apologize, I'm not a native speaker).

The problem is that the argument `dropout` is not always supplied and you would like icontract to ignore the contract if the argument `dropout` is not supplied? What if you have two or more arguments -- wouldn't that be a big pitfall if ignored?

So actually this would require icontract to somehow deal with `args` and `kwargs`: the contract should be something like this:

```
@icontract.require(
    lambda *args, **kwargs: not 'learning_rate' in kwargs or float(kwargs['learning_rate']) > 0.0) 
```
, am I correct?

**Comment by mristin** [comment]
@crypdick @v7a After another take, I realized I had a mistake in my thinking since I always tried to refer to `*args` and `**kwargs` of the function through `*args` and `**kwargs` in the condition (please apologise for the terse and confusing text).

What is actually needed are special arguments allowing the user to refer to positional and keyword arguments of the function call. What do you think of the following solution:

```
@require(
   lambda KWARGS: "learning_rate" not in KWARGS or float(KWARGS["learning_rate"]) > 0)
```
?

KWARGS will be passed whatever keyword arguments there were in the call. Analogously for ARGS.

**Comment by crypdick** [comment]
@mristin right, the idea is that there is no guarantee than any single arg or kwarg will be supplied since they are all optional.

If I understand correctly, you're suggesting making ARGS and KWARGS reserved words for icontract? I am not sure how that would work in situations like https://github.com/Parquery/icontract/issues/147#issuecomment-735024525 where you're unpacking a different dict name (e.g. `**parameters` instead of `**kwargs`)

**Comment by mristin** [comment]
@crypdick could you please have a look at PR #147, at least the tests? Would that work for your use case?

**Comment by crypdick** [comment]
I've reviewed, that looks good!

**Comment by mristin** [comment]
@crypdick let's wait for a week for the next minor release.
