### ISSUE TITLE
[Question] Good training to learn how to use icontract for design-by-contract

### ISSUE THREAD

**Issue by simkimsia** [Parquery/icontract#271]
I read this

> Learning curve. In our experience, it does not take long for programmers to pick up and start applying design-by-contracts. Although only anecdotal, we observed that it takes junior programmers one to two weeks to get up to speed and start writing meaningful contracts in their code.

from https://icontract.readthedocs.io/en/latest/recipes.html

I still find it a bit intimidating to incorporate icontract in my private Django projects.

Was wondering if there's more reading materials elsewhere I can read to learn how to better incorporate icontract for design-by-contract?

**Comment by mristin** [comment]
@simkimsia Sure!

> I still find it a bit intimidating to incorporate icontract in my private Django projects.

Could you maybe narrow down what you find intimidating so that I can give you a bit more targeted literature / advice?

I usually recommend this blog post when I introduce people to DbC: https://bertrandmeyer.com/2018/05/24/not-program-right/

It explains really well in my opinion how to apply the methodology (contracts instead of haphazard debugging). 

However, applying the methodology blindly, just as any other methodology & all other good things in life, should be done in moderation. Maybe that is intimidating you?

When I write code or coach others in DbC, I always tell them to write the obvious contracts first. Then, on a second pass, say, before the code review, write one more contract whenever it makes sense. Start with the trivial stuff: not none, positive, non-negative, a variable in a given range, some item in a given set *etc.*

Maybe you can also peek into how we solved the coding problems for Advent of Code annotated with contracts:
https://github.com/mristin/python-by-contract-corpus

The accompanying paper might be interesting as well: https://dl.acm.org/doi/abs/10.1145/3540250.3558917

One good book that comes to my mind is [Touch of Class](https://touch.ethz.ch/) which was used as the introductory material when I just started the university.

**Comment by simkimsia** [comment]
Thank you, @mristin 
I'll go through the list of links

I have started with checking for not none and then writing an extra unit test to make sure ViolationError is thrown

Do you think writing to check for the ViolationError is overkill?

**Comment by mristin** [comment]
Hi @simkimsia ,
>  I have started with checking for not none and then writing an extra unit test to make sure ViolationError is thrown
>
> Do you think writing to check for the ViolationError is overkill?

I think it is, indeed. My approach is to write unit tests for properties of inputs/outputs which I can not check in contracts. The assumption is that you either get the condition to be checked right or you don't  -- no matter whether you write it in form of a contract or an unit test.

This applies to simpler preconditions. However, if you have very complex preconditions then it does make sense to check them with unit tests.

> Would you recommend it regardless? I think it's not quite as useful if I cannot try the exercises in Touch of Class without Eiffel Studio.

I think I only read the book cover-to-cover and did not do any exercises, but it's been some 20 years ago...

**Comment by mristin** [comment]
(I'm closing the issue as there is no further activity and the issue seems resolved.)
