### ISSUE TITLE
TypeError when using dataclasses.field

### ISSUE THREAD

**Issue by remexre** [Parquery/icontract#288]
```python
>>> @dataclass
... @invariant(lambda self: self.x > 0)
... class Foo:
...     x: int = field(default=42)
... 
>>> Foo(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/8wg14i81qgjf0baaw6a55qidjspayaxc-python3-3.11.6-env/lib/python3.11/site-packages/icontract/_checkers.py", line 966, in wrapper
    instance = new_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object.__new__() takes exactly one argument (the type to instantiate)
```

**Comment by mristin** [comment]
@remexre thanks for reporting the issue!

Where does the `field` come from?

**Comment by remexre** [comment]
It's part of dataclasses: https://docs.python.org/3/library/dataclasses.html#dataclasses.field

**Comment by mristin** [comment]
@remexre I hope I got it right: it seems to me that the order of the decorators matter; icontract can not re-decorate the methods that ``dataclasses`` module inserts.

I also documented the issue for future reference: https://icontract.readthedocs.io/en/latest/known_issues.html#dataclasses

Please feel free to re-open the issue if it indeed turns out that the order of the decorators does not fix your issue.
