### ISSUE TITLE
require decorator removes type annotations for mypy

### ISSUE THREAD

**Issue by jamescasbon** [Parquery/icontract#93]
```
$ cat ic.py  
from icontract import require

@require(lambda x: x > 0)
def f1(x: int): return x

def f2(x: int): return 0

f1("this is wrong")
f2("this is too")

$ mypy ic.py              
ic.py:9: error: Argument 1 to "f2" has incompatible type "str"; expected "int"
```

Both function calls are invalid types but mypy only sees the call as f2 as wrong.  The decorator loses the type annotations?

Related https://github.com/python/mypy/issues/3157

**Comment by mristin** [comment]
(Let me do a couple of experiments. I think I misread https://github.com/python/mypy/issues/3157)

**Comment by mristin** [comment]
Hi @jamescasbon 

My bad, I indeed misread https://github.com/python/mypy/issues/3157. Mypy indeed supports  decorators which do not change the signature of the function.

Would you mind reviewing the following snippet for me? I assume that I simply need to change the argument type and return type of `icontract.require` and `icontract.ensure` argument to fix the issue?

experiment.py:
```python
from typing import TypeVar, Any, Callable

CallableT = TypeVar('CallableT', bound='Callable')

class some_decorator:
    def __init__(self, some_param: int)->None:
        return

    def __call__(self, func: CallableT) -> CallableT:
        def result(*args, **kwargs):
            print("hello")
            return func(*args, **kwargs)

        return result  # type: ignore

@some_decorator(some_param="oi")
def f(x: int, y: str)->str:
    return str(x + int(y))

f(x="oi", y=1)
```

I get the expected errors:

```bash
$ mypy experiment.py 
experiment.py:16: error: Argument "some_param" to "some_decorator" has incompatible type "str"; expected "int"
experiment.py:20: error: Argument "x" to "f" has incompatible type "str"; expected "int"
experiment.py:20: error: Argument "y" to "f" has incompatible type "int"; expected "str"
```

**Comment by jamescasbon** [comment]
Amazing work, yes the branch works with mypy now :+1: 

Thanks for the quick turnaround.

**Comment by jamescasbon** [comment]
Ah, i redid the check with mypy --strict 

The require decorator now gives this error: 

    ic.py:3: warning: Returning Any from function declared to return "bool"

I do think this PR is a lot better - but would be very nice if we could run with strict

**Comment by mristin** [comment]
Hi James,
Let me have a look at it tonight (CET).

Cheers Marko

Le mer. 23 janv. 2019 à 11:05, James Casbon <notifications@github.com> a
écrit :

**Comment by mristin** [comment]
Hi @jamescasbon,
I think this is an issue with how `mypy` handles lambdas.

`icontract.require`'s signature is:

```python
class require:  # pylint: disable=invalid-name
    def __init__(self,
                 condition: Callable[..., bool],
                 description: Optional[str] = None,
                 a_repr: reprlib.Repr = icontract._globals.aRepr,
                 enabled: bool = __debug__,
                 error: Optional[Union[Callable[..., Exception], type]] = None) -> None:
                     ...
```

As you can see, it expects condition to be of type `Callable[..., bool]`, whereas lambdas are inferred as `Callable[..., Any]` since the type of the input argument is not known (see https://mypy.readthedocs.io/en/latest/kinds_of_types.html#callable-types-and-lambdas). 

If you replace it with `def ...`, everything works, see the commit:
https://github.com/Parquery/icontract/pull/94/commits/928d74992f9fb65ae0d0f77f51579fc279390044

Now, I'm not really sure what is the best approach. I expect that typing the condition as `Callable[..., Any]` would confuse the user, but on the other hand would make the `mypy --strict` pass. I'd prefer to stick with the clear type annotations rather than make `mypy --strict` pass. However, if `mypy --strict` is something many people are using then it is a barrier I would not like icontract to introduce.

Please double-check the latest commit and if everything is clear/working OK, let me bump the patch version.

**Comment by jamescasbon** [comment]
Hmmmm.  To be honest I don't know how many people are using mypy --strict.  I am using DBC + mypy to get correctness so my aim would be strict.  3.6 can type lambdas but not anonymous ones :/  

Seems to me if you expect condition to be a lambda you should match the type of a lambda but I appreciate it is not an easy choice.

**Comment by mristin** [comment]
(@jamescasbon -- just a kind reminder; I'd like to wait for you to check that the latest commit fixes your problem before I bump the patch version.)

**Comment by jamescasbon** [comment]
Thanks very much this looks great.  I think you should ship it :+1:
